language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:kalakris/cmake -y; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -q; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y cmake; fi
  - if [ $TRAVIS_OS_NAME == osx]; then brew update; fi

script:
  - cmake -H. -Bbuild
  - cd build
  - make

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - daniel.underwood13@gmail.com
    on_success: change
    on_failure: always
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
