language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ] sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME == linux ] sudo apt-get upgrade -y cmake; fi
  - if [ $TRAVIS_OS_NAME == osx] brew update; fi
  - if [ $TRAVIS_OS_NAME == osx] brew upgrade cmake; fi

script:
  - cmake -H. -Bbuild
  - cd build
  - make

os:
  - linux
  - osx

notifications:
  email:
    recipients:
      - daniel.underwood13@gmail.com
    on_success: change
    on_failure: always
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
